version: '3.7'

services:
  django:
    container_name: wm_api_prod
    command: >
      bash -c "gunicorn website_monitor.wsgi:application --bind 0.0.0.0:8000 --timeout 90 --workers 3
      & python manage.py rqworker default
      & rqscheduler --host wm_redis --port 6379 --db 0 --interval 10"

  nginx:
    container_name: wm_nginx_prod
    build:
      context: .
      dockerfile: docker/nginx/prod.Dockerfile
    volumes:
      - wm_ssl_certs:/usr/src/certs
      - wm_frontend_dist:/usr/src/frontend/dist
      - wm_backend_static:/usr/src/backend
    ports:
      - "443:443"
    depends_on:
      - sslcerts

  frontend:
    container_name: wm_frontend_prod
    command: npm run build
    volumes:
      - wm_frontend_dist:/app/dist

  sslcerts:
    container_name: wm_sslcerts
    build:
      context: .
      dockerfile: docker/ssl/Dockerfile
    command: >
      bash -c "/usr/src/certs/dehydrated/dehydrated --register --accept-terms
      && /usr/src/certs/dehydrated/dehydrated --cron --challenge dns-01 --hook 'hooks/cloudflare/hook.py'"
    volumes:
      - wm_ssl_certs:/usr/src/certs/dehydrated/certs
    env_file:
      - docker/ssl/.env

volumes:
  wm_frontend_dist:
  wm_ssl_certs:
