# Generated by Django 2.1.2 on 2018-10-15 08:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('interval', models.PositiveIntegerField(choices=[(60, '1 min'), (120, '2 min'), (300, '5 min'), (600, '10 min'), (1200, '20 min'), (1800, '30 min'), (3600, '1 hour'), (7200, '2 hours'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=60, verbose_name='Interval')),
                ('check_task_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Check task UUID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='CheckTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('DEGRADED', 'Degraded')], max_length=4, verbose_name='URL status')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Response status code')),
                ('response_time', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Response time (seconds)')),
                ('date_received', models.DateTimeField(auto_now=True, verbose_name='Date received')),
                ('response_content', models.TextField(blank=True, verbose_name='Response content')),
                ('check_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CheckTask', verbose_name='Check task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='checktask',
            unique_together={('url', 'interval')},
        ),
    ]
