# Generated by Django 2.1.2 on 2018-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181016_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktask',
            name='job_id',
            field=models.CharField(blank=True, max_length=36, unique=True, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='checktask',
            name='interval',
            field=models.PositiveIntegerField(choices=[(60, '1 min'), (120, '2 min'), (300, '5 min'), (600, '10 min'), (1200, '20 min'), (1800, '30 min'), (3600, '1 hour'), (7200, '2 hours'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=3600, verbose_name='Interval'),
        ),
    ]
