# Generated by Django 2.1.2 on 2018-10-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181029_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktaskjob',
            old_name='is_scheduled',
            new_name='is_deleted',
        ),
    ]
