# Generated by Django 2.1.2 on 2019-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktask',
            name='last_response_status',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='checktask',
            name='last_response_status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
