# Generated by Django 2.1.2 on 2019-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190221_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checktask',
            name='last_response_status_code',
        ),
    ]
